export { MainPage } from './MainPage/MainPage';
export { ChatListPage } from './ChatListPage/ChatListPage';
export { ChatRoomPage } from './ChatRoomPage/ChatRoomPage';
export { SearchPage } from './SearchPage/SearchPage';
export { SearchResultPage } from './SearchResultPage/SearchResultPage';
export { VideoUploadPage } from './VideoUploadPage/VideoUploadPage';
export { ProfilePage } from './ProfilePage/ProfilePage';
export { AdminPage } from './AdminPage/AdminPage';
export { OnBoardingPage } from './OnBoardingPage/OnBoardingPage';
